### PR TITLE
[overview] Include for studies vis a "-studies" in the id and title

### PR DESCRIPTION
**Pull request by acs**
git pair programming study is normaly not present, so it must not be
included in Overview if the default case. This change modifies the
id and title for visualizations of this study to specify that it is
a study vis:

git_pair_programming_title -> git-study_pair_programming_title

This solution can be used in general so kidash knows what vis are
for studies, and to decide if they must be included.

### CODE REVIEW

**Comment by dicortazar** [comment]
Thanks for the patch!

However, I've realized that other issues may appear with this approach. This change only applies to the summary of the git pair programming widget, but not to the other two: evolution of commits and evolution of authors.

As those widgets are coming from the standard git panel, how are you planning to remove those?

**Comment by acs** [comment]
Hmm, good point. evolution of commits and evolution of authors vis ids must be changed also to:

* git_study_pair_programing_evolution_commits
* git_study_pair_programing_evolution_authors

and that vis must be created. Is that ok for you?

**Comment by acs** [comment]
Ok, I have modified the Overview panel in blue5 and then exported the panel with kidash with:

`(acs@dellx) (studies-ids-titles $% u=) ~/devel/panels-fork-acs/json $ kidash -e https://bitergia:XXXXX@blue5.biterg.io/data --export overview.json --dashboard Overview
`

The result panel is what i have included in this PR. Is that ok  @dicortazar ?

**Comment by alpgarcia** [comment]
LGTM, thanks!

**Comment by acs** [comment]
Amazing! Time to use it. Thank you guys!

**Pull request merged**
